name: Win wheel build

on:
  workflow_dispatch:
  push:
    branches:
      - win-build-wheel

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        platform: [windows-latest]
        python-version: ["3.10.11"]
        cuda-version: ["12.4.1"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: build-env

      - name: Install oneCCL and other dependencies
        # shell: bash -el {0}
        run: |
          conda install -c https://software.repos.intel.com/python/conda/ -c conda-forge oneccl-devel
          python -m pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cu124
          python -m pip install wheel ninja numpy psutil setuptools==72.2.0

      - name: Setup CUDA
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: ${{ matrix.cuda-version }}
          method: local

      - name: Set CUDA paths for Linux
        if: runner.os == 'Linux'
        run: |
          echo "PATH=/usr/local/cuda-12.4/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV


      - name: Set CUDA paths for Windows
        if: runner.os == 'Windows'
        run: |
          echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;${env:PATH}" >> $env:GITHUB_ENV
          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" >> $env:GITHUB_ENV
          echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" >> $env:GITHUB_ENV

      - name: Build the wheel
        shell: cmd
        run: build_win.bat

      - run: du -h dist/*
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl